/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 02.04.2026 04:25:33

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 10272;
#else
constexpr int kTensorArenaSize = 9248;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,4018 } };
const TfArray<1, float> quant0_scale = { 1, { 0.00390625, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 98, 41, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 98, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 49, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 49, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 400, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data6[3] = { 4341, -2351, -1626, };
const TfArray<1, int> tensor_dimension6 = { 1, { 3 } };
const TfArray<1, float> quant6_scale = { 1, { 1.8467142581357621e-05, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[3*400] = { 
  -13, 15, 35, -1, -27, 15, -45, -24, -49, -9, -7, -67, -6, -7, 2, 26, -27, -10, 8, 34, -1, 40, 3, 7, -54, -46, -14, -78, -30, 4, 19, -28, -48, 31, -14, 29, 29, -28, -110, 46, -44, -84, -26, -58, 12, 21, 7, 6, -50, 17, -18, 6, 0, -21, -66, 14, -26, -81, -4, -89, -8, 40, -19, 0, -46, 28, 0, 71, -16, 27, -63, -2, -62, -50, -77, -36, -21, 57, -7, 7, -64, -16, 29, 33, 22, -16, -41, 13, -52, -24, -69, -56, -23, 27, 2, 4, -36, 6, 23, 35, -5, 12, -72, 25, -23, -85, -54, -62, -4, 52, -7, 34, -69, 43, 15, -1, 37, 26, -93, 38, -7, -75, -19, -87, -40, 47, 6, -5, -48, 12, -7, 51, 53, -22, -62, 14, -10, -85, -15, -41, -1, 55, -9, 12, -74, 41, 3, 41, 69, -4, -30, 6, -35, -79, -22, -50, 11, 10, 19, 46, -40, 11, -14, 41, 73, 9, -40, 24, -19, -37, -37, -23, 4, 38, 24, 64, -85, 29, 28, 25, 116, -31, -84, 43, -33, -29, -44, -58, -41, 63, 23, 60, -48, 59, -23, 29, 104, -16, -66, 79, -53, -33, -40, -75, -12, 28, 44, 99, -74, -8, -14, 35, 84, -27, -92, 20, -2, -42, -37, -56, -26, 44, 19, 77, -102, 29, -2, 19, 59, -13, -54, 14, -3, -28, -32, -47, -25, 59, -8, 38, -70, 46, -26, 19, 56, -24, -74, 45, -31, -48, -40, -25, 9, 64, -6, 43, -36, 5, 26, 46, 8, -27, -29, 29, -51, -12, -15, -18, 6, 27, 19, 48, -54, 5, 15, -5, 45, -32, -25, -9, -40, -55, -47, -66, 10, 53, -2, 35, -83, 23, 39, -13, 14, -13, -53, 42, -15, -74, -45, -59, -7, 75, 22, 58, -63, 3, 8, -2, 7, 22, -53, 30, -36, -10, -58, -73, -12, 33, 2, 23, -9, -7, 14, 11, 65, 4, -74, 47, -36, -61, -48, -95, 12, 56, 14, 22, -93, 29, -5, 48, 11, 16, -34, 39, 5, -64, -20, -44, 19, 39, 24, 24, -80, 3, 14, 4, 69, 26, -58, 36, -22, -63, -9, -36, 12, 28, -12, 67, -67, 13, 34, 30, 32, 40, -56, 34, -11, -22, -69, -17, -50, 55, -12, 32, -87, 9, -21, 2, -21, -13, -59, -24, -40, -43, -24, -61, -42, -29, 20, 48, 
  45, 21, -21, -53, -10, -24, 17, -26, -3, -8, -42, 16, -30, -7, 13, 53, 27, 27, -53, -9, 41, -40, 3, -5, -4, -7, 10, 42, -28, -32, 32, -12, 61, 23, -57, -55, 76, -69, -9, 31, 7, -13, -62, 3, -44, -28, 30, 49, 55, 21, -55, -45, 47, -47, 11, 11, -5, 3, -64, 2, -6, -9, 29, 49, 90, 40, -40, -48, 77, -65, 49, 16, -11, 28, -53, 36, -21, -8, 34, 43, 32, -4, -36, -58, 43, -30, 16, 22, 17, 18, -61, 19, -25, 25, 21, 19, 1, -13, -9, 8, -7, -38, 9, -8, 8, 1, -43, 46, -28, -50, 10, 17, 43, -7, -6, -34, 41, -38, 64, 10, 5, 47, -48, -5, -4, -60, 33, -19, 42, 6, -59, -43, 9, -54, 37, -33, -18, 4, -50, 31, 13, -76, 66, 1, 30, 5, -17, -31, -25, -34, 46, -46, -7, 30, -26, 20, -39, -71, 31, -10, 69, 9, -48, -11, -13, -50, 55, -38, -24, 23, -63, 32, -1, -99, 65, -45, 83, -52, -45, -13, -61, -17, 67, -33, 7, 34, -3, 5, -32, -78, 47, -17, 51, -31, -26, -36, -13, -23, 34, 11, 6, 4, 30, 57, 16, -63, 23, -67, 63, -43, -31, -22, -10, -30, -12, -25, 6, 46, -2, 38, 2, -54, 7, -17, 18, 18, -8, 11, 19, -25, 54, -35, 49, 24, 5, 50, 31, -71, 38, -26, 50, 5, -5, -13, 25, -44, 56, 9, -10, -10, 17, 60, 24, -57, 8, -24, 57, -18, -38, -42, -5, -50, 7, 20, 15, 22, -27, 33, -20, -63, 31, 23, 39, 27, -25, -26, 44, -68, 11, -35, 16, 40, -19, 4, -25, -65, 15, 6, 69, -9, -12, -67, 9, -70, 13, 1, 9, -5, -3, -14, -11, -83, 23, 29, 54, 19, -49, -36, 57, -54, 22, -2, 14, 28, -33, 25, -38, -53, 16, 45, 56, 42, -46, 13, 65, -40, 22, 13, 22, 42, -71, -11, -38, -83, 42, 49, 76, -16, -25, -64, 29, -78, 14, 38, -16, -4, -62, 12, -70, -90, 65, 25, 66, 0, -39, -44, 68, -39, 20, 10, -34, 5, -94, -17, -25, -55, 65, 44, 44, -12, -11, -15, 1, -71, 3, -5, 23, 21, -65, 24, -50, -25, 39, 24, 59, 11, -44, -34, 21, -72, 30, -43, -9, 22, -33, -17, 17, -48, 85, -11, 
  -28, -11, 51, 5, -47, 0, 9, -26, 51, 34, 86, 2, 28, 31, -10, -38, 6, -28, 30, 42, -39, 56, 44, -42, -13, 51, 64, 51, 40, -19, -10, -10, -24, -34, 45, 8, -65, 46, 55, -11, 18, -1, 54, 56, 54, -33, -61, -98, -16, -63, 31, -3, -52, 23, -4, -6, 25, 54, 80, 38, 34, -35, -83, -79, -1, -3, 43, 22, -92, 35, 15, -9, -2, 5, 43, 39, 57, 2, -90, -101, -35, -9, 65, -20, -40, 14, -5, -8, 30, 61, 41, 25, 38, 26, -34, -30, -34, -20, 27, 41, -43, 70, 13, -6, 51, -2, 3, -3, 0, 2, -17, 20, -64, -37, 53, -10, -81, 72, 38, -4, 33, -24, 48, -14, -14, -14, -72, -77, -17, -7, 22, 9, -50, 25, 18, -30, -5, 1, 14, 26, 50, -14, -52, -65, -39, -28, 57, 46, -43, 35, 33, -35, -8, 40, 48, 7, -11, 2, -56, -63, -4, -3, 27, 26, -95, 50, 16, -16, 28, -22, 38, 24, 16, -11, -76, -32, -6, -36, 70, 34, -96, 22, 31, 12, 2, -3, 46, 24, 35, 11, -45, -40, 20, -17, 34, 2, -26, 37, 41, 15, 22, 28, 32, 18, 1, -7, -48, -65, -20, -26, 31, -6, -82, 38, 26, -28, 21, 5, 7, 18, 39, 17, -27, -58, -21, -17, 38, 1, -122, 23, 8, -38, 43, -15, 58, 48, -6, -2, -59, -43, -22, 33, -19, 17, -62, 37, 13, -31, 36, 35, 47, 44, 19, -25, -59, -46, -35, 3, 12, 26, -70, 42, -13, 1, -3, 38, 0, 35, -12, -50, -46, -88, -39, -15, 21, -6, -119, 52, -7, -53, -15, -3, 53, 9, 5, -9, -78, -51, -43, 10, -8, 4, -127, -3, -6, 12, -4, -29, 51, -15, -17, 26, -84, -39, -11, -28, 5, 15, -127, 51, 30, 2, 42, -3, 24, 10, -6, 6, -34, -36, -31, 1, 20, -1, -104, 31, 21, 0, 26, 43, 50, 12, 39, -29, -55, -47, -12, -24, 26, 14, -87, 42, 19, 10, -6, -1, 70, 39, 58, -1, -44, -55, -21, 5, 62, 6, -65, 61, 48, -34, -4, 1, 67, 15, 46, 17, -76, -81, -10, 33, 49, -7, -24, 64, 0, 2, 19, 15, 42, 47, 17, 20, -23, -24, -58, 12, 29, 31, -67, 1, -12, -15, 1, 13, 33, 17, 65, 14, -53, -22, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 3,400 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0030228924006223679, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { -3683, 183, -1264, 1513, 4457, 833, -510, 2294, -5947, -5288, 2044, -2263, 477, 5627, 2372, 3986, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 2.5985827960539609e-05, 2.0835199393332005e-05, 2.3833437808207236e-05, 2.0661720554926433e-05, 2.8491023840615526e-05, 2.4236109311459586e-05, 2.0955507352482527e-05, 2.0802986909984611e-05, 1.967413118109107e-05, 1.958499888132792e-05, 2.3629485440324061e-05, 2.932273673650343e-05, 1.9924036678276025e-05, 1.9315148165333085e-05, 2.6591347705107182e-05, 2.5743629521457478e-05, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ 39,-17,88,79,-89,-5,56,-36, 9,-38,36,-7,-122,10,104,-117, 43,-8,54,38,-127,-28,92,-54, 
  /* [1][0][][] */ -1,118,70,12,32,-43,4,12, -13,27,28,-24,93,123,76,54, 127,67,101,-59,-17,-15,10,-33, 
  /* [2][0][][] */ -61,12,-54,10,31,-33,-47,92, 58,-7,9,39,42,-73,-46,127, -95,16,12,-44,-4,-4,-1,44, 
  /* [3][0][][] */ 68,-15,12,-40,127,-32,-69,77, 46,-34,-44,40,57,-43,-57,52, -35,32,-39,-43,99,-21,57,63, 
  /* [4][0][][] */ 15,23,58,-23,-24,36,48,12, -11,42,60,-25,0,121,54,-18, 67,91,119,-23,-25,127,17,3, 
  /* [5][0][][] */ -84,38,12,57,14,-94,-93,124, -110,31,-50,-28,80,46,-127,25, -89,66,-3,33,36,-13,-116,98, 
  /* [6][0][][] */ 49,-48,-56,98,-125,-70,45,9, 0,-105,-38,-49,-92,-46,46,31, -49,-115,-127,105,-72,-44,-20,-66, 
  /* [7][0][][] */ -8,127,44,-96,-40,126,61,32, 81,122,120,35,90,106,19,48, 38,61,-14,-47,116,64,76,22, 
  /* [8][0][][] */ -9,-127,24,68,-21,-77,62,26, -44,-105,-111,64,29,-60,-86,71, -58,-99,17,50,-22,13,-24,-31, 
  /* [9][0][][] */ 4,-106,-23,96,-99,14,67,13, -16,-98,-97,-41,-78,0,9,-8, -3,-113,-127,116,-94,-19,15,30, 
  /* [10][0][][] */ -109,-46,-95,33,41,-69,-30,36, -123,-60,-90,-8,-1,-102,-114,72, -50,-2,-103,56,-10,-3,-84,127, 
  /* [11][0][][] */ -83,-12,-106,91,11,-32,-24,-32, -45,-76,-69,28,21,-100,1,14, -36,-45,-127,69,-80,-92,-20,-24, 
  /* [12][0][][] */ -127,37,-100,98,2,-25,9,47, 10,-18,-110,-35,-66,27,-119,36, 9,54,35,15,41,-91,-106,115, 
  /* [13][0][][] */ 35,48,-25,-14,-18,77,-62,23, 81,106,-48,-5,-34,-50,-62,-8, -2,72,97,-11,127,-36,-65,108, 
  /* [14][0][][] */ 91,34,112,-19,-21,71,72,-70, 42,84,127,8,-19,35,101,-67, 105,-34,74,53,3,-25,70,-79, 
  /* [15][0][][] */ 101,91,85,-28,22,73,5,23, 24,45,127,-25,29,42,37,5, 10,10,124,-28,-37,70,48,11, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.0038306245114654303, 0.0030713598243892193, 0.003513336181640625, 0.0030457868706434965, 0.0041999206878244877, 0.0035726949572563171, 0.0030890945345163345, 0.0030666112434118986, 0.0029002043884247541, 0.0028870650567114353, 0.0034832712262868881, 0.0043225251138210297, 0.0029370433185249567, 0.0028472859412431717, 0.0039198854938149452, 0.0037949215620756149, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { 21093, 22109, 41021, -26027, 15666, 40906, 24528, -2567, };
const TfArray<1, int> tensor_dimension10 = { 1, { 8 } };
const TfArray<8, float> quant10_scale = { 8, { 9.5771774795139208e-06, 9.7246138466289267e-06, 9.6116673375945538e-06, 9.1502761279116385e-06, 9.2490809038281441e-06, 8.2393817137926817e-06, 9.5496507128700614e-06, 9.599446457286831e-06, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*41] = { 
  /* [0][0][][] */ -6,59,-15,20,-55,10,63,-32,-2,8,25,-87,17,-110,-104,21,-9,-38,-13,-78,13,-26,2,72,40,19,41,-75,29,-40,-73,62,35,-41,62,-1,47,10,60,97,56, 15,-64,36,-28,-28,99,40,-24,22,101,74,-92,23,5,43,73,27,-24,53,-75,36,7,-24,1,-43,78,14,56,-27,-18,69,-48,-55,-22,32,58,58,-20,35,79,21, 45,-55,60,-84,-59,-10,-29,53,2,-50,20,-105,-127,-53,-91,-36,45,-68,35,-44,-21,-3,-16,-42,-90,37,1,-57,-59,-38,-18,-44,-21,-35,-14,77,74,80,-48,-11,21, 
  /* [1][0][][] */ -82,-37,-16,104,-28,98,-64,27,3,5,-9,-45,39,-97,67,28,-74,-26,65,62,29,-66,8,32,38,-49,-64,-6,-48,7,16,-77,-65,9,1,54,-35,-45,18,-40,88, -11,-39,25,25,127,86,86,-47,-26,-9,-1,51,-90,-96,56,20,-62,-33,-48,25,73,-66,-45,-72,3,9,-33,10,58,-31,6,2,54,-23,-33,-31,10,8,-60,88,-32, -3,-31,-95,95,99,36,-76,-34,-66,57,91,-53,-31,-15,-33,54,66,-23,-60,-2,-96,5,13,84,-30,84,-22,-47,29,-53,28,-77,-81,29,29,8,-43,51,15,81,-41, 
  /* [2][0][][] */ 61,100,-102,1,-58,-65,40,17,-49,6,43,-68,54,-74,-56,70,60,-75,54,15,73,-17,-20,45,24,-35,-30,-75,25,-62,-80,52,-71,37,85,-79,21,-81,-34,-56,31, 3,9,-68,31,24,47,-56,44,-79,75,-80,-42,15,94,54,-75,-58,56,53,-4,65,-62,-25,-10,79,-13,29,-67,-50,-18,62,-57,29,-48,-53,-127,21,-88,-83,29,-74, -71,-14,42,-2,116,104,44,-97,-93,-48,22,42,9,52,-73,-66,86,-94,33,27,-76,5,59,-37,1,-26,35,70,60,-10,0,-55,61,-69,-4,69,-77,-69,9,36,-65, 
  /* [3][0][][] */ -61,-33,5,-103,22,-60,73,65,53,-76,-22,-58,19,73,37,-7,84,19,50,18,42,86,80,41,-4,57,64,-81,94,44,30,48,83,48,50,26,-52,-15,-97,33,-92, -26,-29,-27,3,-12,46,-36,127,35,-55,-33,-34,-17,113,-32,74,66,-8,50,49,24,18,93,-28,-88,43,-53,0,-8,76,68,24,19,-23,-19,-16,-80,56,-50,35,-35, 54,-90,37,9,-26,-23,-68,72,57,-61,-89,6,-46,57,26,-5,-26,54,-51,27,-59,45,-22,-34,30,13,69,-82,86,-29,-13,-15,-18,9,26,-81,-96,-40,16,-99,-50, 
  /* [4][0][][] */ 48,-47,-39,94,-28,17,-1,12,-5,-18,-51,53,17,20,-21,83,-46,-41,-70,-57,-24,-79,-64,15,-21,-9,-16,58,35,-30,-24,30,-109,-43,19,-33,-12,96,1,67,92, -13,57,-67,-30,18,74,-45,-45,-15,-20,52,-21,34,-74,-11,-39,23,55,-49,-19,55,51,61,3,113,20,-37,23,57,-80,96,-74,-127,50,21,-19,45,-45,42,114,-35, -87,-3,-75,-1,81,40,-37,-117,-19,65,73,77,-98,-9,-67,-37,13,25,-12,-8,3,-52,-15,-42,-7,-11,-35,92,32,-84,93,35,-127,46,58,86,13,-49,26,25,-10, 
  /* [5][0][][] */ -12,74,-2,92,111,58,-47,-32,-26,58,-33,83,-9,43,-45,5,-95,23,-40,53,-58,-41,67,-30,-23,-87,23,43,-78,86,-114,111,26,-42,60,-17,-55,-73,69,-53,-69, -64,99,78,87,31,-43,-40,-122,-77,-100,-78,-15,55,-57,-17,-12,-20,90,65,39,-58,21,38,-9,16,-66,74,27,25,-63,-13,-50,55,-76,-47,-15,61,-52,-98,64,-55, 107,29,18,60,26,-14,26,57,39,15,-26,55,-89,8,63,-57,-3,-106,27,53,-77,11,-60,-11,71,76,20,-45,-4,67,-36,-84,-65,-104,-26,-127,2,70,-34,82,16, 
  /* [6][0][][] */ 42,75,-24,19,-26,-20,-41,-38,-29,-48,-66,-5,-78,-43,-13,-11,-24,56,32,-8,-35,41,-16,47,-59,36,127,-8,53,9,-20,-43,85,-72,-43,42,-69,73,-63,-22,-15, -103,31,-20,-63,72,57,49,36,75,-14,61,-108,6,64,-78,-36,-60,38,78,-41,-92,-22,-29,-61,58,22,85,-59,-8,101,46,-43,98,-70,79,90,69,-64,-60,26,-28, -59,-16,-86,-62,-17,-10,94,91,-26,-30,-5,-74,-79,-73,63,-42,44,-34,14,-76,48,-5,16,19,-114,29,27,26,-16,30,-29,93,40,85,-2,-52,-67,43,-17,-53,2, 
  /* [7][0][][] */ 64,2,46,45,76,19,-77,4,-55,-65,82,-38,77,-62,14,37,7,121,-37,18,13,29,-50,-22,96,-59,-59,94,41,22,6,-60,-22,68,-30,-54,39,-14,62,-41,-32, 16,-39,-21,-41,-31,15,24,-53,-20,28,-57,56,13,-73,-6,-50,-20,44,-76,7,49,33,42,-9,22,-78,-12,67,-68,-124,11,27,-44,50,-22,6,23,-19,35,1,-37, -18,-23,-38,-1,21,1,-38,-22,-49,-31,-48,51,50,58,58,66,55,37,-24,71,83,55,-39,74,72,19,-68,80,-3,13,-24,-44,-127,12,-102,-55,35,21,-14,-66,28, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,41 } };
const TfArray<8, float> quant11_scale = { 8, { 0.0024517574347555637, 0.0024895011447370052, 0.0024605868384242058, 0.0023424706887453794, 0.0023677647113800049, 0.0021092817187309265, 0.0024447105824947357, 0.0024574582930654287, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,98,41 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,98,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.0067837052047252655, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,98,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,49,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,49,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,49,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.0061090970411896706, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,49,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,25,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,400 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,3 } };
const TfArray<1, float> quant21_scale = { 1, { 0.10254920274019241, } };
const TfArray<1, int> quant21_zero = { 1, { 36 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 4032), (TfLiteIntArray*)&g0::tensor_dimension0, 4018, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 1200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 984, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 4018, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 4032), (TfLiteIntArray*)&g0::tensor_dimension13, 784, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 784, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 784), (TfLiteIntArray*)&g0::tensor_dimension15, 392, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 392, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 784), (TfLiteIntArray*)&g0::tensor_dimension17, 784, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 784, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 784), (TfLiteIntArray*)&g0::tensor_dimension19, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension21, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_942602_7_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_942602_7_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_942602_7_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_942602_7_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_942602_7_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
